@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lordmonoxide.gradient.progression;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
