@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lordmonoxide.gradient.core.tileentities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
