@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lordmonoxide.gradient.blocks.bronzeboiler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
