@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lordmonoxide.gradient.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
