@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lordmonoxide.gradient.blocks.clayfurnace;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
