@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lordmonoxide.gradient.blocks.standingtorch;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
