@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lordmonoxide.gradient.entities;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
