@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lordmonoxide.gradient.integrations.jei.shapeless;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
