@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lordmonoxide.gradient.science.chemistry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
