@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lordmonoxide.gradient.blocks.claybucket;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
